title: Trevor Flower's Homepage
author: Trevor Flower
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  This is used to test out making my own webpage for myself

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
